SOURCE: synthia
TARGET: Cityscapes
NUM_CLASSES: 19
NUM_WORKERS: 4
DA_METHOD: FDA
restore_opt1: ../../experiments/snapshots/synthia52Cityscapes_DeepLab_MobileNet_FDA_0.01/model_100000_0.01.pth
restore_opt2: ../../experiments/snapshots/synthia2Cityscapes_DeepLab_MobileNet_FDA_0.05/model_100000_0.05.pth
restore_opt3: ../../experiments/snapshots/synthia52Cityscapes_DeepLab_MobileNet_FDA_0.09/model_100000_0.09.pth
SAVE: ../../experiments/pseudolabels



